### PR TITLE
Show the rejected version to help track bugs down

### PR DESCRIPTION
**Pull request by batmat**
Example with this change:

```
(node:1) UnhandledPromiseRejectionWarning: Error: Invalid argument not valid semver ('1.0-rc50.78d526a2ba0f' received)
```

Thanks!

### CODE REVIEW

**Review by omichelsen — CHANGES_REQUESTED** [review]
Thanks for the PR.

Could you change the syntax to regular string concatenation as the script is not pre-parsed and template literals does not work in IE and older versions of other browsers.

**Comment by batmat** [comment]
Done, thanks a lot @omichelsen :)

**Comment by omichelsen** [comment]
Last ask and I'll merge, could you squash your commits with a message in this style: "feat(error): show rejected version in error message"

Just to keep it compatible with the angular commit message pattern so we can auto generate changelogs. I will add a contributing file explaining these things better :-)

**Comment by batmat** [comment]
@omichelsen can try, though not familiar with Angular style. But wouldn't it as easy in such case that you would just from GitHub squash the PR and write the log commit as you think suits best?

**Comment by batmat** [comment]
Done @omichelsen

**Comment by omichelsen** [comment]
You are right, have not played much with the GitHub options :)

Thanks for the contribution!

**Comment by toolmantim** [comment]
👏🏼 Thanks for this change!

**Pull request merged**
