### PR TITLE
feat: use TypeScript

### PR DESCRIPTION
**Pull request by omichelsen**
Due to inconsistencies in maintaining the CJS and ESM version of this package separately, we're moving to TypeScript to be able to build two identical output bundles. This should also keep types more in sync with code changes.

This PR is open to comments and reviews. Once tested more thoroughly it's expected to be released a v5.

### CODE REVIEW

**Comment by jvanderen1** [comment]
I have this repo where I rewrote compare-versions in typescript. If you want to take any inspiration from it, feel free to use anything: https://github.com/jvanderen1/compare-versions

**Comment by jlarmstrongiv** [comment]
Would this PR still support commonjs?  I like how https://github.com/jvanderen1/compare-versions keeps that support

**Comment by jvanderen1** [comment]
I went ahead and published [@jvanderen1/compare-versions](https://www.npmjs.com/package/@jvanderen1/compare-versions)!

**Comment by omichelsen** [comment]
> Would this PR still support commonjs? I like how https://github.com/jvanderen1/compare-versions keeps that support

Yes, we intend to support CJS (through UMD) as well as ESM.

**Pull request merged**
